import ToastProvider from '@/providers/toast-provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/header/navbar';
import TanstackProvider from '@/providers/tanstack-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TanstackProvider>
          <ToastProvider />
          <Navbar />
          <main className='container pt-12 h-screen'> {children}</main>
        </TanstackProvider>
      </body>
    </html>
  );
}
